#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

declare -a commands=(
    "yarn build"
    "npx cypress run"
    "npx eslint"
    "yarn test --watchAll=false"
)
declare -i progress=1

RED='\033[0;36m'
NC='\033[0m'

for i in "${!commands[@]}"
do  
    echo -e "\n${RED}Pre Commit Progress : [""${progress}/${#commands[@]}""]\n${NC}"
    eval "${commands[$i]}"
    ((progress++))
done
