#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

logFileName="pre-commit-test-logs.txt"
set -o pipefail
echo "" | tee $logFileName
echo "--------------------------" | tee -a $logFileName
echo "Starting Pre Commit Tests." | tee -a $logFileName
echo `date +"%A, %Y-%m-%d %T"` | tee -a $logFileName
echo "--------------------------" | tee -a $logFileName
echo "" | tee -a $logFileName


declare -a commands=(
    "yarn build"
    "npx cypress run"
    "npx eslint --fix ./src/**/*.{tsx,ts}"
    "npx stylelint src/**/*.css"
    "yarn test --watchAll=false"
)
declare -i progress=1

RED='\033[0;31m'
BLUE='\033[0;36m'
GRAY='\033[1;30m'
NC='\033[0m'
BGreen='\033[1;32m'

for i in "${!commands[@]}"
do  
    echo -e "\n${BLUE}Running Pre Commit test : [""${progress}/${#commands[@]}""]${NC}"
    echo -e "${GRAY}${commands[$i]}\n${NC}"
    echo "Running ${commands[$i]}" >> $logFileName
    eval "${commands[$i]}" | tee -a $logFileName || { echo -e "\n${RED}${commands[$i]} Failed!\nSee ${logFileName} for details.\n${NC}"; exit 212; }
    echo -e "${BGreen}Passed [""${progress}/${#commands[@]}""]${NC}\n"
    ((progress++))
done

